server:
  port: 8188
  servlet:
    context-path: /winter-market-auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/winter-market
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: nik.noreply.b@mail.ru
    password: 29ffGaF9btVHgBeAeGgx

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://192.168.1.110:8080/realms/master
#          jwk-set-uri: http://192.168.1.110:8080/realms/master/protocol/openid-connect/certs

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none

jwt:
  secret: 5agwerDFHgp0weg703utjSFJDshbsHHio3njc234rypnc998t7bhn36AZBNGUK34056jvg0359DBGNJDTN4vnt035tn938457v
  lifetime: 36000000