server:
  port: 8189
  servlet:
    context-path: /winter-market-core

spring:
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/winter-market?options=--search_path%3Dwinter-market
    user: postgres
    password: admin
    validate-on-migrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/winter-market?options=--search_path%3Dwinter-market
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none

integrations:
  cart-service:
    url: http://localhost:8190/winter-market-carts/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000